add 2.1, 2.2, 2.3
apcc/lets-make-minigames pull request #10
Opened 2019-12-15 15:08 UTC by su8ru

issue: #3

2019-12-15 15:50 UTC, ibuki2003 requested changes
こんなもんかなぁ
特にクラスはクラスであることを押し出して行くほうがいいとおもうので

2019-12-15 15:50 UTC, ibuki2003 commented on 2/3.md
> +しかし、ウィンドウを出す処理をしていないので、これを実行してもウィンドウは出ないのである。
プログラムが即終了するだけでウィンドウは作られるのでは
ゲームとして成り立たないのでループを書こう がよいとおもいます

2019-12-15 15:50 UTC, ibuki2003 commented on 2/2.md
> +![](./images/2-2-2_1.png)
色が違うこともあるのでそこを注釈いれたいかな 以下(?)同様

2019-12-15 15:50 UTC, ibuki2003 commented on 2/2.md
> +左側のファイルツリーから `Source Files` > `Main.cpp` を開いてみよう。
左とは限らないし何なら普通は右
ソースファイルはカタカナになってなかったけ?これは気のせいかも

2019-12-15 15:50 UTC, ibuki2003 commented on 2/2.md
> +場所は自分でわかりやすい場所にするべき。あとから探すのは大変なので…
みんなデスクトップに置く気がした
今はデフォルトが`~/source/repo/`になってそれなりにわかりやすいはずなのでここでよくないですか

2019-12-15 15:50 UTC, ibuki2003 commented on 2/2.md
> +画像のように`OpenSiv3D(0.4.2)`を選択したら、「次へ」。
バージョンによる差異があるのでそこを幅持たせたい
```suggestion
画像のように`OpenSiv3D(0.4.2)`(バージョンはこれと異なることがあるが気にしなくてよい)を選択したら、「次へ」。
```

2019-12-15 15:50 UTC, ibuki2003 commented on 2/3.md
> +ここでは文字列を扱うための`String`型を用いて`Hello, Siv3D!`と表示する。`String`型は`U"hoge"`で記述できる。`U`を忘れないように注意。
Stringはクラスであることを主張するとわかりやすい気がする。
クラスは型みたいなもんだけどメソッドとかいろいろあるからクラスとして認識しておくのが吉かなぁ

あと細かいことを言うと`U""`は`const char32_t*` 結局同等に扱えるし暗黙キャストできるしこれはStringとしてもいいか…

```suggestion
ここでは文字列を扱うためにSiv3Dに用意されたクラス`String`を用いて`Hello, Siv3D!`と表示する。`String`は`U"hoge"`とすること作ることができる。`U`を忘れないように注意。
```

2019-12-15 15:50 UTC, ibuki2003 commented on 2/3.md
> +- `Range(begin, end)`: beginからendまでの配列を返す。
Rangeが返すのは配列ではなくGeneratorです 扱いは実質同じだけど一応。
正確に begin以上end未満の整数とか言いたい

2019-12-15 15:50 UTC, ibuki2003 commented on 2/3.md
> +	Print << Range(0, 10);
`Print << Array({1,2,3,4,5})` としてArrayが配列として扱えるSiv3D特設のクラスというのがよさそう

2019-12-15 15:50 UTC, ibuki2003 commented on 2/3.md
> +- `Vec2(x, y)`: 2次元座標。3次元もあるよ。
Vec2もクラスです
```suggestion
- `Vec2(x, y)`: x,yの2つの実数をメンバに持って2次元座標を表すクラス。3次元もあるよ。
```

2019-12-15 15:50 UTC, ibuki2003 commented on 2/1.md
> +  開発者本人に質問ができたり、イベントの情報も知れる。入るべき。
ほんと? こっちに聞いてくれたほうがハードル低くて精神衛生上よいのでは 「入るべき」は強い気がした

2019-12-16 01:23 UTC, su8ru commented on 2/3.md
> +しかし、ウィンドウを出す処理をしていないので、これを実行してもウィンドウは出ないのである。
あってるじゃねえか

2019-12-16 03:00 UTC, ibuki2003 approved these changes
よいとおもいます

2019-12-16 03:54 UTC, merged