0章1章かいた
apcc/lets-make-minigames pull request #4
Opened 2019-12-12 17:23 UTC by ibuki2003

URLがすごくシンプルで困惑しています、はい…()

2019-12-12 18:52 UTC, su8ru requested changes
`0/1.md` および `0/2.md` がですます調になってる
統一したさ

2019-12-12 18:53 UTC, su8ru commented
vectorとかは後々紹介？

2019-12-12 18:53 UTC, ibuki2003 commented
wakaru

2019-12-13 00:33 UTC, ibuki2003 commented
vectorは ミニゲームには使わないかなーって

2019-12-13 06:55 UTC, su8ru approved these changes

2019-12-13 16:22 UTC, merged